# Global settings
compress
copytruncate
notifempty
missingok
size 50M
rotate 5
maxage 30

# Frontend logs
/var/log/frontend/*.log {
    daily
    dateext
    dateformat -%Y%m%d
    postrotate
        docker kill -s USR1 lpr-frontend
    endscript
}

# Backend logs
/var/log/backend/*.log {
    daily
    dateext
    dateformat -%Y%m%d
    postrotate
        docker kill -s USR1 lpr-backend
    endscript
}

# License plate detection service logs
/var/log/license-plate-service/*.log {
    daily
    dateext
    dateformat -%Y%m%d
    postrotate
        docker kill -s USR1 lpr-detection
    endscript
}

# Nginx logs
/var/log/nginx/*.log {
    daily
    dateext
    dateformat -%Y%m%d
    postrotate
        docker kill -s USR1 lpr-loadbalancer
    endscript
}

# MongoDB logs
/var/log/mongodb/*.log {
    daily
    dateext
    dateformat -%Y%m%d
    postrotate
        docker kill -s USR1 lpr-mongodb
    endscript
}

# Redis logs
/var/log/redis/*.log {
    daily
    dateext
    dateformat -%Y%m%d
    postrotate
        docker kill -s USR1 lpr-redis
    endscript
}